global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "otel-collector"
    scrape_interval: 5s
    static_configs:
      - targets: ["otel-collector:8889"]

  - job_name: "fastapi-app"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["app:8000"]

  - job_name: "cassandra"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["cassandra:7072"]

rule_files:
  - '/etc/prometheus/rules.yml'